### PR TITLE
Paging

### PR DESCRIPTION
**Pull request by jmcclelland**
Enable ability to manage hundreds of inbound SMS messages via paging. Note - this PR incorporates my other PR. If you accept my original PR I can refactor this one to only include the commit with the pager changes.

### CODE REVIEW

**Comment by JohnFF** [comment]
Hi Jamie,

Thank you for doing this: it looks great at first glance.

I have a new build arriving imminently, whereupon I'll be able to test and
review this more thoroughly. Once I've tested it I will merge and create a
new release.

And then we can get it added to the store!

Cheerio,

John

**Comment by JohnFF** [comment]
Hi,

I have checked this out and I'm getting the following error repeatedly:

Notice: Undefined index: custom_88 in CRM_Smsinbox_Page_SmsInbox->setMessageInformation() (line 12 of /var/www/bedsafe_live/sites/default/files/civicrm/ext/sms-inbox/CRM/Smsinbox/Page/SmsInbox.php).

Please resolve this,

John

**Comment by jmcclelland** [comment]
Thanks for checking it out and providing feedback!

Is it possible you are not pulling in the entire PR? From a look at the [page in question](https://github.com/JohnFF/SMS-Inbox/pull/4/files#diff-42aca4d7cc48884234212b791af4b348fbe09d6d31c21e72e2a8a3b5c39646ec) it seems that the old line 12 - which should be removed - is `$inboundSmsActivity['read'] = $inboundSmsActivity[$this->messageReadCustomFieldId];`. I can imagine that line throwing the error you are receiving. However, the new line 12 should be: `if (isset($_GET['crmPID'])) {` - which couldn't throw that error.

There really shouldn't be any reference to any custom fields in the new code.

**Comment by JohnFF** [comment]
It's possible I did a bad checkout. I'll give it another go and see.

**Pull request merged**
